### ISSUE TITLE
get 'TypeError' while using MAM.create()

### ISSUE THREAD

**Issue by HexRabbit** [iotaledger-archive/outdated-mam.client.js#17]
node version: v9.3.0

Run the post.js in examples dir and than get this error message.
```
bundle.addEntry(signatureFragments.length, address, value, tag, timestamp);
                                       ^
TypeError: Cannot read property 'length' of null
    at new create (/home/hexshift/mam.client.js/lib/mam.js:103:40)
    at Object.<anonymous> (/home/hexshift/mam.client.js/examples/post.js:25:13)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```
From debugger I can tell it's caused by 
`const cipher = Encryption.encrypt(messageOut, options.channelKey, salt)` 
in MAM.create(), 
I found options.channelKey is null and edit channelKey to some random 81 chars key,
but still get same error.
I can reproduce it in every try running post.js.

**Comment by lelmac** [comment]
Hi,
the issue is produced by a wrong dependency of iota.crypto.js. The one used hasn't got the constant curl.HASH_LENGTH. This results in empty hashes and thus it is not working. Not sure if it would be useful to open a pull request, since this is declared dead.
